language: python
python:
  - "3.6" 
before_install:
  - python --version
  - pip install pip
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report=xml --cov=deeptabular WUT/tests/
# after success
after_success:
  - codecov
